pt_osc:
  charset: utf8mb4
  recursion_method: "dsn=D=<db>,t=dsns"
  no_swap_tables: true
  chunk_size: 1000
  max_lag: 1.5
  statistics: true
  dry_run: false

pt_osc_threshold: 1000

alert:
  metadata_lock_threshold_seconds: 30

session_config:
  lock_wait_timeout: 10
  innodb_lock_wait_timeout: 10
